/**
 * JSON-EXEMPLE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Categorie } from './categorie';


export interface Produit {
    id?: number;
    codeProduit?: string;
    nomProduit?: string;
    typeProduit?: string;
    dateProduit?: Date;
    categorie?: Categorie;
}
